version: '3.3'
services:
  api:
    image: registry.test.com/mapotempo/optimizer-api:latest
    hostname: travis-api
    environment:
      REDIS_RESQUE_HOST: redis
      REDIS_HOST: redis-cache
      APP_ENV: test
    networks:
      - base
      - redis_cache
      - resque

  resque-default:
    image: registry.test.com/mapotempo/optimizer-api:latest
    working_dir: /srv/app
    hostname: travis-resque-default
    environment:
      APP_ENV: test
      COUNT: 5
      QUEUES: DEFAULT
      REDIS_HOST: redis-cache
      REDIS_RESQUE_HOST: redis
      ROUTER_API_KEY: ${ROUTER_API_KEY:-demo}
      ROUTER_URL: ${ROUTER_URL:-http://localhost:4899/0.1}
    command: bundle exec rake resque:workers
    networks:
      - redis_cache
      - resque

  redis:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    hostname: travis-redis
    volumes:
      - ../redis:/data
    command: redis-server --appendonly yes
    networks:
      - resque

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    hostname: travis-redis-cache
    volumes:
      - ../redis:/data
    command: redis-server --save ""
    networks:
      - redis_cache

networks:
  resque:
  redis_cache:
  base:
